version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /home/mongodb:/data/db
    restart: always
    
# Also you can set password for you database, but I don't use that
